---
#envisalink:
envisalink_new:
  #-
  #                  _           _ _       _
  #   ___ _ ____   _(_)___  __ _| (_)_ __ | | __
  #  / _ \ '_ \ \ / / / __|/ _` | | | '_ \| |/ /
  # |  __/ | | \ V /| \__ \ (_| | | | | | |   <
  #  \___|_| |_|\_/ |_|___/\__,_|_|_|_| |_|_|\_\
  #
  #
  #- from github.com/tinuva/home-assistant-config
  host: !secret evl_host
  panel_type: DSC
  user_name: !secret evl_user
  password: !secret evl_pass
  code: !secret evl_pin
  port: 4025
  evl_version: 4
  keepalive_interval: 60
  zonedump_interval: 30
  timeout: 10
  panic_type: Police
  #create_zone_bypass_switches: true
  partitions:
    1:
      name: 'Home Alarm'
  zones:
    1:
      name: 'Front Door'
      type: 'door'
    2:
      name: 'Lounge PIR'
      type: 'motion'
    3:
      name: 'Kitchen PIR'
      type: 'motion'
    4:
      name: 'Study PIR'
      type: 'motion'
    5:
      name: 'Babyroom PIR'
      type: 'motion'
    6:
      name: 'Main Bedroom PIR'
      type: 'motion'
    7:
      name: 'Ensuite PIR'
      type: 'motion'
    8:
      name: 'Front Garage Door/Window'
      type: 'garage_door'
    9:
      name: 'Lounge Window'
      type: 'window'
    10:
      name: 'Kitchen Window'
      type: 'window'
    11:
      name: 'Sculllery Window'
      type: 'window'
    12:
      name: 'Scullery Door'
      type: 'window'
    13:
      name: 'Study Window'
      type: 'window'
    14:
      name: 'Babyroom Window'
      type: 'window'
    15:
      name: 'Main Bedroom Window'
      type: 'window'
    16:
      name: 'Panic'
      type: 'safety'
    17:
      name: 'Spare Bedroom PIR'
      type: 'motion'
    18:
      name: 'Braai-room PIR'
      type: 'motion'
    19:
      name: 'Back Garage PIR'
      type: 'motion'
    20:
      name: 'Back Garage Door'
      type: 'garage_door'
    25:
      name: 'Front Beam'
      type: 'motion'
    26:
      name: 'Back Beam'
      type: 'motion'
    42:
      name: 'Box Tamper'
      type: 'tamper'

# binary_sensor.babyroom_pir
# binary_sensor.babyroom_window
# binary_sensor.back_beam
# binary_sensor.back_garage_door
# binary_sensor.back_garage_pir
# binary_sensor.braai_room_pir
# binary_sensor.ensuite_pir
# binary_sensor.front_beam
# binary_sensor.front_door
# binary_sensor.front_garage_door_window
# binary_sensor.kitchen_pir
# binary_sensor.kitchen_window
# binary_sensor.lounge_pir
# binary_sensor.lounge_window
# binary_sensor.main_bedroom_pir
# binary_sensor.main_bedroom_window
# binary_sensor.scullery_door
# binary_sensor.sculllery_window
# binary_sensor.spare_bedroom_pir
# binary_sensor.study_pir
# binary_sensor.study_window
# binary_sensor.box_tamper
# binary_sensor.panic

group:
  armed_away:
    name: Armed Away Sensors
    entities:
      - binary_sensor.babyroom_pir
      - binary_sensor.babyroom_window
      - binary_sensor.back_beam
      - binary_sensor.back_garage_door
      - binary_sensor.back_garage_pir
      - binary_sensor.braai_room_pir
      - binary_sensor.ensuite_pir
      - binary_sensor.front_beam
      - binary_sensor.front_door
      - binary_sensor.front_garage_door_window
      - binary_sensor.kitchen_pir
      - binary_sensor.kitchen_window
      - binary_sensor.lounge_pir
      - binary_sensor.lounge_window
      - binary_sensor.main_bedroom_pir
      - binary_sensor.scullery_door
      - binary_sensor.sculllery_window
      - binary_sensor.spare_bedroom_pir
      - binary_sensor.study_pir
      - binary_sensor.study_window
  armed_home:
    name: Armed Home Sensors
    entities:
      - binary_sensor.babyroom_window
      - binary_sensor.back_beam
      - binary_sensor.back_garage_door
      - binary_sensor.back_garage_pir
      - binary_sensor.braai_room_pir
      - binary_sensor.front_beam
      - binary_sensor.front_door
      - binary_sensor.front_garage_door_window
      - binary_sensor.kitchen_window
      - binary_sensor.lounge_window
      - binary_sensor.scullery_door
      - binary_sensor.sculllery_window
      - binary_sensor.study_window
  armed_night:
    name: Armed Night Sensors
    entities:
      - binary_sensor.babyroom_window
      - binary_sensor.back_beam
      - binary_sensor.back_garage_door
      - binary_sensor.back_garage_pir
      - binary_sensor.braai_room_pir
      - binary_sensor.front_beam
      - binary_sensor.front_door
      - binary_sensor.front_garage_door_window
      - binary_sensor.kitchen_pir
      - binary_sensor.kitchen_window
      - binary_sensor.lounge_pir
      - binary_sensor.lounge_window
      - binary_sensor.scullery_door
      - binary_sensor.sculllery_window
      - binary_sensor.spare_bedroom_pir
      - binary_sensor.study_window

sensor:
  - platform: template
    sensors:
      armed_home:
        friendly_name: Armed Home
        value_template: >-
          {%- for entity_id in states.group.armed_home.attributes.entity_id if states(entity_id) == 'on' -%}
          {% set parts = entity_id.split('.') -%}
          {% set sensor_name  = (states[parts[0]][parts[1]].name | replace(' - alarm',''))    %}
          {%- if loop.first %}{% elif loop.last %} {{- '\n' -}} {% else %} {{- '\n' -}} {% endif -%}
          {% if ('DOORS' in sensor_name|upper or 'WINDOWS' in sensor_name|upper ) %}{{ sensor_name }} opened{% elif ('DOOR' in sensor_name|upper or 'WINDOW' in sensor_name|upper ) %}{{ sensor_name }} opened{% else %}{{ sensor_name }} triggered{% endif %}
          {%- endfor %}

  - platform: template
    sensors:
      armed_away:
        friendly_name: Armed Away
        value_template: >-
          {%- for entity_id in states.group.armed_away.attributes.entity_id if states(entity_id) == 'on' -%}
          {% set parts = entity_id.split('.') -%}
          {% set sensor_name  = (states[parts[0]][parts[1]].name | replace(' - alarm',''))    %}
          {%- if loop.first %}{% elif loop.last %} {{- '\n' -}} {% else %} {{- '\n' -}} {% endif -%}
          {% if ('DOORS' in sensor_name|upper or 'WINDOWS' in sensor_name|upper ) %}{{ sensor_name }} opened{% elif ('DOOR' in sensor_name|upper or 'WINDOW' in sensor_name|upper ) %}{{ sensor_name }} opened{% else %}{{ sensor_name }} triggered{% endif %}
          {%- endfor %}
