---

cover:
  ## Front Garage Door
  - platform: template
    covers:
      garage_door_front:
        device_class: garage
        friendly_name: "Garage Door Front"
        position_template: "{{ is_state('binary_sensor.front_garage_door_window', 'on') }}"
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garagedoor_front_garagedoor_front
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garagedoor_front_garagedoor_front
        stop_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garagedoor_front_garagedoor_front
        icon_template: >-
          {% if is_state('binary_sensor.front_garage_door_window', 'on') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}

  # Back Garage Door
  - platform: template
    covers:
      garage_door_back:
        device_class: garage
        friendly_name: "Garage Door Back"
        position_template: "{{ is_state('binary_sensor.back_garage_door', 'on') }}"
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garagedoor_back_garagedoor_back
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garagedoor_back_garagedoor_back
        stop_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garagedoor_back_garagedoor_back
        icon_template: >-
          {% if is_state('binary_sensor.back_garage_door', 'on') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}

## Alert
alert:
  garage_door_front:
    name: Front Garage Door is open
    #done_message: Front Garage is closed
    #entity_id: binary_sensor.front_garage_door_window
    entity_id: input_boolean.front_garage_after_dark
    state: 'on'   # Optional, 'on' is the default value
    repeat:
      - 15
      - 30
      - 60
    skip_first: true  # Optional, false is the default
    notifiers:
      - notify_garagedoor_front
  garage_door_back:
    name: Back Garage Door is open
    #done_message: Back Garage is closed
    #entity_id: binary_sensor.back_garage_door
    entity_id: input_boolean.back_garage_after_dark
    state: 'on'   # Optional, 'on' is the default value
    repeat:
      - 15
      - 30
      - 60
    skip_first: true  # Optional, false is the default
    notifiers:
      - notify_garagedoor_back

command_line:
  - notify:
      name: notify_garagedoor_front
      command: "/config/ha_to_api_notify_cover.sh script.notify_garagedoor_front"
  - notify:
      name: notify_garagedoor_back
      command: "/config/ha_to_api_notify_cover.sh script.notify_garagedoor_back"

### Scripts
script:
  notify_garagedoor_front:
    sequence:
      - service: script.notify_slack
        data_template:
          channel: "C012KCJ9YJ0"
          message: "The Front Garage door is open."
          attachments:
            - title: Close the Front Garage door?
              callback_id: cover_left_open_callback
              color: '#03a9f4'
              attachment_type: default
              actions:
                - text: Close it
                  value: Close it
                  name: 'cover.garage_door_front'
                  type: button
                - text: Leave it
                  value: Leave it
                  name: 'anything_just_not_blank'
                  type: button
  notify_garagedoor_back:
    sequence:
      - service: script.notify_slack
        data_template:
          channel: "C012KCJ9YJ0"
          message: "The Back Garage door is open."
          attachments:
            - title: Close the Back Garage door?
              callback_id: cover_left_open_callback
              color: '#03a9f4'
              attachment_type: default
              actions:
                - text: Close it
                  value: Close it
                  name: 'cover.garage_door_back'
                  type: button
                - text: Leave it
                  value: Leave it
                  name: 'anything_just_not_blank'
                  type: button

group:
  garage_doors:
    name: Garage Doors
    entities:
      - binary_sensor.front_garage_door_window
      - binary_sensor.back_garage_door

input_boolean:
  # This switch turns on if the garage is open after dark and triggers the garage_after_dark alert.
  front_garage_after_dark:
    name: Front Garage Open After Dark
    icon: mdi:message-alert
  back_garage_after_dark:
    name: Back Garage Open After Dark
    icon: mdi:message-alert

automation:
  # If garage doors are closed kick off script to turn them off, and turn off alert.
  - id: front_garage_closed
    alias: Front Garage Closed
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.front_garage_door_window
        from: 'on'
        to: 'off'
    action:
      #- service: script.driveway_off
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.front_garage_after_dark

  # If garage is still open at 10:30pm turn on alart to make sure it get closed.
  - id: front_close_garage_lights_out
    alias: Close Front Garage at lights out
    initial_state: true
    trigger:
      - platform: time
        at: '20:00:00'
      - platform: state
        entity_id: binary_sensor.front_garage_door_window
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.front_garage_door_window
        state: "on"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.front_garage_after_dark

  # If garage doors are closed kick off script to turn them off, and turn off alert.
  - id: back_garage_closed
    alias: Back Garage Closed
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.back_garage_door
        from: 'on'
        to: 'off'
    action:
      #- service: script.driveway_off
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.back_garage_after_dark

  # If garage is still open at 10:30pm turn on alart to make sure it get closed.
  - id: back_close_garage_lights_out
    alias: Close Back Garage at lights out
    initial_state: true
    trigger:
      - platform: time
        at: '20:00:00'
      - platform: state
        entity_id: binary_sensor.back_garage_door
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.back_garage_door
        state: "on"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.back_garage_after_dark
