---
sensor:
  - platform: statistics
    name: "Kitchen Pet Door Battery Average"
    unique_id: kitchen_pet_door_battery_average
    entity_id: sensor.phl_5410ecfffe2281d9_battery
    state_characteristic: mean
    max_age:
      hours: 24
    keep_last_sample: true

automation:
  ### Notify state change
  - alias: Notify when kitchen pet door state change
    description: Notify when kitchen pet door state change
    trigger:
      - entity_id: sensor.phl_5410ecfffe2281d9_lock_state_sensor
        platform: state
    condition:
      - condition: template
        value_template: >
          {{ trigger.from_state.state != trigger.to_state.state }}
      - condition: template
        value_template: >
          {{ trigger.from_state.state != "unavailable" }}
      - condition: template
        value_template: >
          {{ trigger.to_state.state != "unavailable" }}
      - condition: template
        value_template: >
          {{ trigger.from_state.last_changed != trigger.to_state.last_changed }}
    action:
      - service: script.alert
        data:
          icon: ':cat2:'
          object: 'Kitchen Pet Door'
          message: >
            Kitchen Pet Door lock state changed to: {{ states('sensor.phl_5410ecfffe2281d9_lock_state_sensor') }}

  - alias: Notify when kitchen pet door battery low
    description: Notify when kitchen pet door battery low
    trigger:
      - platform: numeric_state
        entity_id: sensor.kitchen_pet_door_battery_average
        below: '20'
    condition:
      - condition: template
        value_template: >
          {{ trigger.from_state.state != trigger.to_state.state }}
      - condition: template
        value_template: >
          {{ trigger.from_state.state != "unavailable" }}
    action:
      - service: script.alert
        data:
          icon: ':cat2:'
          object: 'Kitchen Pet Door Battery'
          message: >
            Kitchen Pet Door battery below 20%: {{ states('sensor.kitchen_pet_door_battery_average') }}%
