---

light:
  - platform: group
    unique_id: lights_stay_on_with_guest_mode
    name: Lights stay on with guest mode
    entities:
      - light.front_bathroom
  - platform: group
    unique_id: lights_whole_night
    name: Lights whole night
    entities:
      - light.outside_kitchen_outside_kitchen
  - platform: group
    unique_id: lights_while_awake
    name: Lights while awake
    entities:
      - light.braai_courtyard
  - platform: group
    name: Lights while awake with guests
    unique_id: lights_while_awake_with_guests
    entities:
      - light.dining_l1 # light.lounge_courtyard
      - light.main_bedroom_courtyard
      - light.scullery_outside
      - light.main_bedroom_outside
      # - light.pool_pool

automation:
  ## Whole night
  - alias: "Turn on outside lights and check every minute - whole night"
    trigger:
      - platform: time_pattern
        # You can also match on interval. This will match every x minutes
        minutes: "/1"
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.grid_mode
            state: '4'
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            #after_offset: "00:20:00"
          - condition: sun
            before: sunrise
            #before_offset: "-00:20:00"
    action:
      - service: light.turn_on
        entity_id:
          - light.lights_whole_night

  ## Whole day
  - alias: "Turn off outside lights and check every minute - whole night"
    trigger:
      - platform: time_pattern
        # You can also match on interval. This will match every x minutes
        minutes: "/1"
    condition:
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: sun
                after: sunrise
                #after_offset: "-00:20:00"
              - condition: sun
                before: sunset
                #before_offset: "00:20:00"
          - condition: state
            entity_id: sensor.grid_mode
            state: '4'
    action:
      - service: light.turn_off
        entity_id:
          - light.lights_whole_night

  ## While awake
  - alias: "Turn on outside lights and check every minute - while awake"
    trigger:
      - platform: time_pattern
        # You can also match on interval. This will match every x minutes
        minutes: "/1"
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: disarmed
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            #after_offset: "00:20:00"
          - condition: sun
            before: sunrise
            #before_offset: "-00:20:00"
    action:
      - service: light.turn_on
        entity_id:
          - light.lights_while_awake
      - condition: state
        entity_id: input_boolean.guest
        state: 'on'
      - service: light.turn_on
        entity_id:
          - light.lights_while_awake_with_guests


  ## While not awake
  - alias: "Turn off outside lights and check every minute - while not awake"
    trigger:
      - platform: time_pattern
        # You can also match on interval. This will match every x minutes
        minutes: "/1"
    condition:
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: sun
                after: sunrise
                #after_offset: "-00:20:00"
              - condition: sun
                before: sunset
                #before_offset: "00:20:00"
          - condition: state
            entity_id: alarm_control_panel.home_alarm
            state: armed_home
          - condition: state
            entity_id: alarm_control_panel.home_alarm
            state: armed_night
          - condition: state
            entity_id: alarm_control_panel.home_alarm
            state: armed_away
    action:
      - service: light.turn_off
        entity_id:
          - light.lights_while_awake
          - light.lights_while_awake_with_guests
          # - light.pool_pool
