---
timer:
  # When calling the start service on a timer that is already running, it resets
  # the duration it will need to finish and restart the timer without triggering
  # a canceled or finished event. This, for example, makes it easy to create
  # timed lights that get triggered by motion. Starting a timer triggers a
  # started event unless the timer is paused, in that case, it triggers a
  # restarted event.
  scullery:
    duration: '00:10:00'
  main_ensuite:
    duration: '00:10:00'

automation:
  # Timer end = Turn off
  - alias: Light Power Save Trigger
    description: Turn off light when timer ends
    mode: parallel
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.main_ensuite
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.scullery
    action:
      - service: light.turn_off
        data_template:
          entity_id: "{{ trigger.event.data.entity_id|replace('timer.', 'light.') }}"

  - alias: Light Power Save Timer
    description: Start timer if turned on
    mode: parallel
    trigger:
      - platform: state
        entity_id: light.main_ensuite, light.scullery_scullery
        to: 'on'
    action:
      - service: timer.start
        data_template:
          entity_id: "{{ trigger.entity_id|replace('light.', 'timer.') }}"
          duration: '00:10:00'
