generate_suggestions:
  name: Generate Suggestions
  description: "Manually trigger AI automation suggestions."
  fields:
    provider_config:
      name: Provider Configuration
      description: Which provider configuration to use (if you have multiple configured)
      required: false
      selector:
        config_entry:
          integration: ai_automation_suggester
    custom_prompt:
      name: Custom Prompt
      description: Optional custom prompt to override or enhance the default system prompt.
      required: false
      example: "Focus on energy-saving automations"  
      selector:
        text:
          multiline: true
    all_entities:
      name: Consider All Entities
      description: "If true, consider all entities instead of just new entities."
      required: false
      default: false
      selector:
        boolean: {}
    domains:
      name: Domains
      description: "List of domains to consider. If empty, consider all domains."
      required: false
      selector:
        object: {}
      default: {}
    entity_limit:
      name: Entity Limit
      description: "Maximum number of entities to consider (randomly selected from the chosen domains)."
      required: false
      default: 200
      selector:
        number:
          min: 50
          max: 1000
          mode: slider
