---
automation:
  - alias: "Dreame Vacuum: Daily Living Areas Clean"
    description: "Clean kitchen, lounge, front hall and living room at 4:50am"
    mode: single
    trigger:
      - platform: time
        at: "04:50:00"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.xiaomi_robot_vacuum_x20_status
            state: idle
          - condition: state
            entity_id: sensor.xiaomi_robot_vacuum_x20_status
            state: charging
          - condition: state
            entity_id: sensor.xiaomi_robot_vacuum_x20_status
            state: sleeping
      - condition: not
        conditions:
          - condition: state
            entity_id: input_boolean.floor_disaster_zone
            state: "on"
    action:
      # Turn on lights in areas to be cleaned
      - service: light.turn_on
        target:
          entity_id:
            - light.kitchen_kitchen
            - light.lounge_lounge
            - light.lounge_dining
        data: {}
      - service: script.clean_room
        data:
          mode: Vacuum
          room:
            - "11"  # Kitchen
            - "14"  # Lounge
            - "13"  # Front Hall
            - "17"  # Living Room
