trigger:
  target:
    entity:
      integration: nodered
      domain: switch
  fields:
    output_path:
      default: "0"
      example: "1,2"
      selector:
        text:
    message:
      selector:
        object:
