---

automation:
  ### Turn off all lights when Alarm is armed
  - alias: Turn off lights when Alarm is armed
    description: Turn off lights when Alarm is armed
    trigger:
      - entity_id: alarm_control_panel.home_alarm
        platform: state
        to: 'armed_home'
      - entity_id: alarm_control_panel.home_alarm
        platform: state
        to: 'armed_away'
    action:
      - service: light.turn_off
        data_template:
          entity_id: >
            {%- set data = namespace(lights_todo=[]) -%}
            {%- set domains = ['light'] -%}
            {%- for domain in domains -%}
              {%- for item in states[domain]  -%}
                {%- if item.entity_id not in states.light.lights_whole_night.attributes.entity_id and state_attr(item.entity_id, 'icon') == none %}
                  {%- if states.input_boolean.guest.state == "off" or item.entity_id not in states.light.light.lights_stay_on_with_guest_mode.attributes.entity_id %}
                    {%- set data.lights_todo = data.lights_todo + [item.entity_id] %}
                  {%- endif -%}
                {%- endif -%}
              {%- endfor -%}
            {%- endfor -%}
            {{ data.lights_todo | join(",") }}

  ### Lock Pet door if alarm armed away
  #- alias: Lock Pet door if alarm armed away
  #  description: Lock Pet door if alarm armed away
  #  trigger:
  #  - entity_id: alarm_control_panel.home_alarm
  #    platform: state
  #    to: 'armed_away'
  #  action:
  #  - service: surepetcare.set_lock_state
  #    data_template:
  #      flap_id: 204121
  #      lock_state: unlocked

  ### Turn of Lounge TV Systems when Alarm is armed
  #- alias: Turn of Lounge TV Systems when Alarm is armed
  #  description: Turn of Lounge TV Systems when Alarm is armed
  #  trigger:
  #  - entity_id: alarm_control_panel.home_alarm
  #    platform: state
  #    to: 'armed_home'
  #  - entity_id: alarm_control_panel.home_alarm
  #    platform: state
  #    to: 'armed_away'
  #  condition:
  #    - condition: state  # only if it is on
  #      entity_id: remote.harmony_hub
  #      state: 'on'
  #  action:
  #  - service: remote.turn_off
  #    entity_id: remote.harmony_hub
