---
binary_sensor:
  - platform: template
    sensors:
      baby_room_door_closed_long:
        friendly_name: "Baby room door closed long"
        unique_id: baby_room_door_closed_long
        value_template: >-
          {% if states.binary_sensor.baby_room_door_contact.state == 'off' %}
          {% if (as_timestamp(now()) - as_timestamp(states.binary_sensor.baby_room_door_contact.last_changed))/60 > 30 %}
          off
          {% else %}
          on
          {% endif %}
          {% else %}
          on
          {% endif %}

automation:
  ### Notify baby room door opened after closed for long
  - id: '1486327112612'
    alias: Notify baby room door opened after closed for long
    description: Notify baby room door opened after closed for long
    trigger:
      - entity_id: binary_sensor.baby_room_door_closed_long
        platform: state
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.study_pir
        state: 'off'
        for:
          minutes: 2
      - condition: state
        entity_id: binary_sensor.main_bedroom_pir
        state: 'off'
        for:
          minutes: 2
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ ('12:00' < states('sensor.time') < '15:00') }}"
          - condition: template
            value_template: "{{ ('20:00' < states('sensor.time') < '6:00') }}"
    action:
      - service: script.alert
        data:
          target: 'alerts'
          icon: ':rotating_light: '
          object: 'Home Alarm'
          message: "Baby room door opened!"
