---
input_boolean:
  camera_alerts:
    name: Camera Alerts

timer:
  camera_alerts_disabled:
    duration: '00:60:00'
    restore: true

automation:
  # camera alerts disabled - start timer to re-enable
  - alias: Start timer when Camera Alerts disabled
    trigger:
      - platform: state
        entity_id: input_boolean.camera_alerts
        to: 'off'
    action:
      - service: timer.start
        data:
          entity_id: timer.camera_alerts_disabled
      - service: script.alert
        data:
          target: 'alerts'
          icon: ':video_camera: '
          object: 'Camera'
          camera: 'camera.front_camera'
          message: "Camera Alerts disabled for: {{ states.timer.camera_alerts_disabled.attributes.duration|string }}"

  # timer ended, turn camera alerts on
  - alias: Turn camera alerts back on
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.camera_alerts_disabled
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.camera_alerts

  - id: '1686327112618'
    alias: Notify Front Beam Motion
    description: Notify when Front Beam Motion Sensor is triggered
    mode: single # Which is the default but also adds warning to log
    #mode: queued
    #max: 1
    max_exceeded: debug # see if we can remove warning
    trigger:
      - entity_id: binary_sensor.front_beam
        platform: state
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.camera_alerts
        state: 'on'
      # only if front door + front gate + garage doors, closed for at least 30 seconds
      - condition: state
        entity_id: cover.garage_door_front
        state: 'closed'
        for:
          seconds: 30
      - condition: state
        entity_id: cover.garage_door_back
        state: 'closed'
        for:
          seconds: 30
      - condition: state
        entity_id: cover.front_gate
        state: 'closed'
        for:
          seconds: 30
      - condition: state
        entity_id: binary_sensor.front_door
        state: 'off'
        for:
          seconds: 30
    action:
      - service: script.alert
        data:
          target: 'alerts'
          icon: ':video_camera: '
          object: 'Camera'
          camera: 'camera.front_camera'
          message: "Motion detected at Front Beam"
      - delay: '00:00:10' # seconds
