---

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_bot_key
    allowed_chat_ids:
      - "-1001211934352" # CoCT Area 6 loadshedding notifications 1001211934352
      # Error sending message: Group migrated to supergroup. New chat id: -1001211934352. Args: (-461988039, '**
      - "-1001454331987" # ebucks discount notifications

automation:
  - alias: 'MQTT to Telegram - eBucks Deals'
    mode: parallel
    initial_state: true
    trigger:
      - platform: mqtt
        topic: 'telegram/ebucks/discount/+'
    action:
      - service: telegram_bot.send_message
        data_template:
          message: >
            {{ trigger.payload }}
          target: '-1001454331987'
          #target: "-1001211934352"
          parse_mode: markdown
