automation:
  ### Back garage only entrance is through the garage door itself
  ### Back Garage
  # Open = Turn on
  - alias: Turn on back garage lights when door opened
    trigger:
      - platform: state
        entity_id: binary_sensor.back_garage_door
        to: 'on'
    condition:
      - condition: state  # 'night' condition: from sunset until sunrise
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_on
        data:
          entity_id:
            - light.back_garage

  ### Back Garage
  # Close = Turn off
  - alias: Turn on back garage lights when door closed
    trigger:
      - platform: state
        entity_id: binary_sensor.back_garage_door
        to: 'off'
    action:
      service: light.turn_off
      data:
        entity_id:
          - light.back_garage
