---
sensor:
  - platform: statistics
    name: 'Average Temperature Outside last 1 day'
    entity_id: sensor.outside_temperature
    state_characteristic: mean
    max_age:
      days: 1
    keep_last_sample: true
