---
logger:
  logs:
    custom_components.midea_ac: warn #info
    msmart: warn #debug

homeassistant:
  customize:
    climate.midea_ac_30786325862093:
      friendly_name: 'AC Main Bedroom'
    climate.midea_ac_30786325862153:
      friendly_name: 'AC Amy Bedroom'
    climate.midea_ac_32985348871179:
      friendly_name: 'AC Andre Bedroom'

# climate:
#   - platform: midea_ac
#     host: !secret midea_ac1_ip
#     id: !secret midea_ac1_id
#     # v3 need token and k1(key)
#     token: !secret midea_ac1_token
#     k1: !secret midea_ac1_k1
#     prompt_tone: false

#   - platform: midea_ac
#     host: !secret midea_ac2_ip
#     id: !secret midea_ac2_id
#     # v3 need token and k1(key)
#     token: !secret midea_ac2_token
#     k1: !secret midea_ac2_k1
#     prompt_tone: false

#   - platform: midea_ac
#     host: !secret midea_ac3_ip
#     id: !secret midea_ac3_id
#     # v3 need token and k1(key)
#     token: !secret midea_ac3_token
#     k1: !secret midea_ac3_k1
#     prompt_tone: false
