---
mqtt:
  sensor:
    - name: "Weather today max"
      state_topic: "home/weather/today/max"
      unit_of_measurement: '°C'
      device_class: temperature
      unique_id: sensor.weather_today_max
    - name: "Weather today min"
      state_topic: "home/weather/today/min"
      unit_of_measurement: '°C'
      device_class: temperature
      unique_id: sensor.weather_today_min

automation:
  - alias: Weather Forecast to MQTT
    description: Put Weather predicted values in MQTT
    trigger:
      - platform: time
        at: 01:00:00
    condition: []
    action:
      - service: weather.get_forecasts
        data:
          type: hourly
        target:
          entity_id: weather.home
        response_variable: today_hourly
      - variables:
          tomorrow: >-
            {{ (as_timestamp(now().date() + timedelta(days=1)) | timestamp_utc).replace(' ', 'T') ~ '+00:00' }}
      - variables:
          today: >-
            {{ today_hourly['weather.home']['forecast']| selectattr('datetime', 'lt', tomorrow) | map(attribute='temperature') | list }}
      - service: mqtt.publish
        data:
          topic: home/weather/today/max
          payload_template: >
            {{ today | max }}
          retain: true
      - service: mqtt.publish
        data:
          topic: home/weather/today/min
          payload_template: >
            {{ today | min }}
          retain: true
    mode: single
