---

automation:
 # Kitchen button
 - alias: 'MQTT Zigbee Button Kitchen single click'
   initial_state: true
   trigger:
    - platform: mqtt
      topic: 'zigbee2mqtt/Kitchen Button/action'
      payload: 'single'
   action:
    - service: light.toggle
      data:
       entity_id: light.kitchen_kitchen

 - alias: 'MQTT Zigbee Button Kitchen double click'
   initial_state: true
   trigger:
    - platform: mqtt
      topic: 'zigbee2mqtt/Kitchen Button/action'
      payload: 'double'
   action:
    - service: light.turn_on
      data:
       entity_id: light.kitchen_kitchen
       data:
         brightness_pct: 90

 - alias: 'MQTT Zigbee Button Kitchen hold action'
   initial_state: true
   trigger:
    - platform: mqtt
      topic: 'zigbee2mqtt/Kitchen Button/action'
      payload: 'hold'
   action:
    # Mop Kitchen floor
    - service: script.clean_room
      data:
        mode: Mop
        room:
          - "11"

 # Main Bathroom button
 - alias: 'MQTT Zigbee Button Main Bathroom single click'
   initial_state: true
   trigger:
    - platform: mqtt
      topic: 'zigbee2mqtt/Main Bathroom Button/action'
      payload: 'single'
   action:
    - service: light.toggle
      data:
       entity_id: light.main_bathroom

#  # Lounge button
#  - alias: 'MQTT Zigbee Button Lounge hold action'
#    initial_state: true
#    trigger:
#      - platform: mqtt
#        topic: 'tele/zigbee/Lounge Button/Action'
#        payload: 'hold'
#    action:
#      - service: automation.trigger
#        data:
#          entity_id:
#            - automation.set_lights_when_plex_kodi_is_playing
#  - alias: 'MQTT Zigbee Button Lounge single click'
#    initial_state: true
#    trigger:
#      - platform: mqtt
#        topic: 'tele/zigbee/Lounge Button/Click'
#        payload: 'single'
#    action:
#      - service: light.turn_off
#        data:
#          entity_id:
#            - light.lounge_lounge
