esphome:
  name: bluetooth-proxy-03
  friendly_name: bluetooth-proxy-03

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "iiQWvdUSXwt7tcQfLORWQlmjtC1WA/Ah5zP9819Rot4="

ota:
  password: "44fc08955643860f3e11deea01cfb730"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 10.0.22.23
    gateway: 10.0.22.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bluetooth-Proxy-03"
    password: "JHPUFB1ICkmJ"

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

#text_sensor:
#  - platform: ble_scanner
#    name: "BLE Devices Scanner"

bluetooth_proxy:
  active: true

sensor:
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:4B:0A:7B"
    temperature:
      name: "Outside Temperature"
    humidity:
      name: "Outside Humidity"
    battery_level:
      name: "Outside Battery-Level"
    battery_voltage:
      name: "Outside Battery-Voltage"
    signal_strength:
      name: "Outside Signal"
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:8D:C0:E1"
    temperature:
      name: "Andre Bedroom Temperature"
    humidity:
      name: "Andre Bedroom Humidity"
    battery_level:
      name: "Andre Bedroom Battery-Level"
    battery_voltage:
      name: "Andre Bedroom Battery-Voltage"
    signal_strength:
      name: "Andre Bedroom Signal"