esphome:
  name: bluetooth-proxy-03
  friendly_name: bluetooth-proxy-03

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "iiQWvdUSXwt7tcQfLORWQlmjtC1WA/Ah5zP9819Rot4="

ota:
  password: "44fc08955643860f3e11deea01cfb730"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bluetooth-Proxy-03"
    password: "JHPUFB1ICkmJ"

captive_portal:
    