---
sensor:
  - platform: command_line
    name: 'Google Cache Redirector'
    command: "curl -s https://redirector.googlevideo.com/report_mapping?di=no"
    value_template: '{{ value.split("next_hop_address")[0] }}'
    scan_interval: 300

automation:
  - alias: "Google Cache Redirector Update"
    initial_state: 'on'
    trigger:
      - entity_id: sensor.google_cache_redirector
        platform: state
    action:
      - alias: "Alert change"
        service: script.alert
        data:
          icon: ':earth_africa:'
          object: 'Google Cache Redirect update'
          target: 'logs-internet'
          message: >
            From: {{ trigger.from_state.state }} {{- '\n' -}}
            To:   {{ states.sensor.google_cache_redirector.state }}
