group:
  feeds_off_while_sleeping:
    name: Feeds off while sleeping
    entities:
      - switch.office_feed_1
      - switch.office_feed_2

  feeds_off_while_sleeping_without_auto_turn_on:
    name: Feeds off while sleeping
    entities:
      - switch.bar_media_feed

automation:
  ### Turn off feeds when Alarm is armed
  - alias: Turn off feeds when Alarm is armed
    description: Turn off feeds when Alarm is armed
    trigger:
      - entity_id: alarm_control_panel.home_alarm
        platform: state
        to: 'armed_home'
      - entity_id: alarm_control_panel.home_alarm
        platform: state
        to: 'armed_away'
    action:
      - service: switch.turn_off
        entity_id: 
          - group.feeds_off_while_sleeping
          - group.feeds_off_while_sleeping_without_auto_turn_on

  ### Turn on feeds when Alarm is disarmed
  - alias: Turn on feeds when Alarm is armed
    description: Turn on feeds when Alarm is disarmed
    trigger:
      - entity_id: alarm_control_panel.home_alarm
        platform: state
        to: 'disarmed'
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: switch.turn_on
        entity_id: 
          - group.feeds_off_while_sleeping
