---

automation:
  # Kitchen button
  - alias: 'MQTT Zigbee Button Kitchen single click'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: 'tele/zigbee/Kitchen Button/Click'
        payload: 'single'
      - platform: mqtt
        topic: 'zigbee2mqtt/Kitchen Button/action'
        payload: 'single'
    action:
      - service: light.toggle
        data:
          entity_id: light.kitchen
    #  - service: input_boolean.toggle
    #    data:
    #      entity_id: input_boolean.kitchenwork

  - alias: 'MQTT Zigbee Button Kitchen hold action'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: 'tele/zigbee/Kitchen Button/Action'
        payload: 'single'
      - platform: state
        entity_id: sensor.kitchenm_button_action
    condition:
      - condition: template
        value_template: '{{ "hold" == trigger.to_state.attributes.action }}'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.kitchen
          transition: 50
          brightness: >-
            {% set time = states('sensor.time') %}
            {%- if(is_state('input_boolean.kitchenwork','on')) -%}
            185
            {% elif '18:00' <= time <= '20:25' %}
            175
            {% elif '05:30' <= time <= '07:30' %}
            175
            {%- else -%}
            175
            {%- endif -%}

#zigbee2mqtt        | Zigbee2MQTT:info  2022-08-14 19:16:33: MQTT publish: topic 'zigbee2mqtt/Main Bathroom Button/action', payload 'single'
#zigbee2mqtt        | Zigbee2MQTT:info  2022-08-14 19:16:33: MQTT publish: topic 'zigbee2mqtt/Main Bathroom Button/click', payload 'single'

  # Main Bathroom button
  - alias: 'MQTT Zigbee Button Main Bathroom single click'
    initial_state: true
    trigger:
      # - platform: mqtt
      #   #topic: 'tele/zigbee/Main Bathroom Button/Click'
      #   topic: 'zigbee2mqtt/Main Bathroom Button/click'
      #   payload: 'single'
      - platform: state
        entity_id: sensor.main_bathroom_button_action
    condition:
      - condition: template
        value_template: '{{ "single" == trigger.to_state.attributes.click }}'
      - condition: state
        entity_id: timer.main_bathroom
        state: 'idle'
    action:
      - service: automation.trigger
        data:
          skip_condition: true
          entity_id: automation.turn_on_main_bathroom_lights_fan

  - alias: 'MQTT Zigbee Button Main Bathroom single click'
    initial_state: true
    trigger:
      # - platform: mqtt
      #   topic: 'zigbee2mqtt/Main Bathroom Button/click'
      #   payload: 'single'
      - platform: state
        entity_id: sensor.main_bathroom_button_action
    condition:
      - condition: template
        value_template: '{{ "single" == trigger.to_state.attributes.click }}'
      - condition: state
        entity_id: timer.main_bathroom
        state: 'active'
    action:
      - service: timer.cancel
        data:
          entity_id: timer.main_bathroom
      - service: light.turn_off
        data:
          entity_id: light.main_bathroom

# sensor.main_bathroom_button_action

  # - alias: mb button test
  #   trigger:
  #     - platform: state
  #       entity_id: sensor.main_bathroom_button_action
  #   action:
  #     - alias: "Log action taken"
  #       service: script.log
  #       data:
  #         icon: ':zap:'
  #         object: 'mb button'
  #         message: >
  #               State:
  #               {{ trigger.to_state.attributes.click }}

  # Lounge button
  - alias: 'MQTT Zigbee Button Lounge hold action'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: 'tele/zigbee/Lounge Button/Action'
        payload: 'hold'
    action:
      - service: automation.trigger
        data:
          entity_id:
            - automation.set_lights_when_plex_kodi_is_playing
  - alias: 'MQTT Zigbee Button Lounge single click'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: 'tele/zigbee/Lounge Button/Click'
        payload: 'single'
    action:
      - service: light.turn_off
        data:
          entity_id:
            - light.lounge
